language: java
sudo: required
dist: trusty
before_install:
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
matrix:
  include:
  - env: JDK='Oracle JDK 10'
    install: ". ./install-jdk.sh -F 10 -L BCL"
after_success:
- bash <(curl -s https://codecov.io/bash)
- ./gradlew assemble
- docker -v
- docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
- set +e
- export REPO=aista/form-expert
- docker build -t $REPO:$TRAVIS_TAG -t $REPO:latest .
- docker push $REPO
env:
  global:
  - secure: mpb0TZTQ4+tA8B1KYDgydRERgwUilz4rs3ZE3DDW5PoTZQf32lLxRYZGv8yhZG2/FL8a7qSvKz8W9yX4mgbMAChIAvQYfmFXvi68PZFIP7hTXX5WT5Z43HH8Pa12Q9kLd9DJcnWTYcLujYelnuurP66xFqRK9q/BSUl7+HTtH/W4LGd867KCJZyeoUA4AIobBtA5WNDXTIkjo/iU+LUiOEIp2YgdsWEOFTmeA97lWD0t4QpZ7fNXwPLs6gqe4BCkv3S6W3DOyrDzBmDLtokjrmSYKS+oRFD2URQhfDvshW34cqbqSZRl0szpvj9GaEml7rb67SZamDXo+kZMZRymm8c3XnlESehm7cOW0PkTXwzww98nFyx/HGgiWlMs0xc9YWBYuJJ3pR+H988gfPPG6NaXdKev/0uocC0av2hDD67Qnif8co3weMmw3WZPCz7nxE/7/tGnE3iqEYanIXZvjiNRhyE4Cz7ypajj5MOvo6pvycJOvXL3x1mxG5hfP4smSlWBjkJq8xLPie4ECs9mCf7UHSnk5YwCb7HqygIt3Gs3m1NCs50MVgLmGFHeSyvk+BIHzWr38f6DB5RZLb282slBQXYHh8Blq7S6IU3LTE/StQW9or6VF8dsO6gHI7ba15ZuMEVw108To3PyN2WNCFzZEGw/sqbvgwMxLuwZiz4=
  - secure: S6sQL1styK9SP/0L5z41M6oZwZbLqYOsKafX8oGJkp1Ix6GDvAZqXG5K4EJSIm87jBTLj+SiYGt7Z/cY1MipDNByZNaqX3dRTD/QxiG3GYP2BOD2aDGHMopPEWfD3SyYYPhpWMSC6aThZCExYVmzsipJjAvxr4Ff/X+86LjWNptaGN5PujGkOrg7vy2zkpCaBMFqzi/a4+RExBqBMgPucDQLSfLdXwqO5sWr0qgCkrx5KXuHXcSLczn/+RyajfQl1EDw1V+bzYsrY/8gKwwavJJo218c1sbCvemCtzFlTtEPVoytHKxkCtCZtvNW+wopWZaf6P5zrXhbiDLSqPbYvYruqOc6WgT7ZxcOmLdIcKUY1LvH2GTsSGJuYx0KkeafrDx91HthsSiw9GDI6gp2jDIUuNKUmn9ZzRXedkKzRmOA3PeDHjGHyavkkWK0UL2kwKNdYEtiyaYCX1P8YcISssuRp5ME3KJma1wr6k/lxpbBWKVKzezZL4uuqOxeynTEzTUSzdAgPvTYjLxzTr6vDVUnRzZ99aPd0E0Zb3OPU7lIHWduJH/G0l7RvmsPTcBadhIGoHj3TjHIrAM/Rpt/A6Doa64dXdPeeeUXrDvFKzU3W5StmfL30YC74Z4JQLlWllG7AFAPYaC2NgoOMMJmBpkHBk1TjDBa9BWJ0VgsrI4=
