version: "3"

services:
  formexpert:
    build: ./
    ports:
      - '8080:8080'
    depends_on:
      - mappingservice
      - discoveryservice
      - finitehorizonservice
      - generaltypeservice
      - labelmultiplexservice
      - formexpertwarehouse

  mappingservice:
    image: aista/mapping-service
    volumes:
      - ./src:/usr/src/app
    ports:
      - '8082:8080'
    links:
      - mongo
    depends_on:
      - mongo
      - discoveryservice

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'mapping_db'
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      PGDATA: ./postgres-data
    ports:
      - '5432:5432'
    volumes:
      - ./db_volume:/var/lib/postgresql

  finitehorizonservice:
    image: aista/finite-horizon-service
    volumes:
      - ./src:/usr/src/finite-horizon-service
    ports:
      - '8083:8080'
    depends_on:
      - mongo
      - discoveryservice

  generaltypeservice:
    image: aista/general-type-service
    volumes:
      - ./src:/usr/src/general-type-service
    ports:
      - '8084:8080'
    depends_on:
      - mongo
      - discoveryservice

  labelmultiplexservice:
    image: aista/label-multiplex-service:0.11
    volumes:
      - ./src:/usr/src/labelmultiplexservice
    ports:
      - '8085:8080'
    depends_on:
      - postgres
      - discoveryservice

  formexpertwarehouse:
      image: aista/form-expert-warehouse
      volumes:
        - ./src:/usr/src/formexpertwarehouse
      ports:
        - '8086:8080'
      depends_on:
        - mongo
        - discoveryservice

  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER=user
      - MONGODB_PASS=pass
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'

  discoveryservice:
    image: springcloud/eureka
    ports:
      - "8761:8761"

  spacyservice:
    image: aista/spacy-service
    volumes:
      - ./src:/usr/src/spacyservice
    ports:
      - '8087:8080'
    depends_on:
      - discoveryservice